# Generated by Django 4.2.23 on 2025-09-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("counter", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("transcript", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("counter", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("body", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("counter", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("video_url", models.URLField()),
                ("subtitles_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="content_pag_title_1bad05_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Contents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_object_id",
                    models.PositiveIntegerField(
                        db_column="object_id",
                        db_index=True,
                        help_text="ID конкретного объекта выбранного типа контента",
                        verbose_name="ID объекта контента",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Выберите модель контента (Video, Audio, Text и др.)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип контента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
        migrations.CreateModel(
            name="ContentOnPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "alias",
                    models.SlugField(
                        blank=True,
                        help_text="Необязательный alias на странице",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_items",
                        to="content.contents",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="content.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент контента на странице",
                "verbose_name_plural": "Элементы контента на странице",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="contents",
            index=models.Index(
                fields=["content_type", "_object_id"],
                name="content_con_content_412e8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentonpage",
            index=models.Index(
                fields=["page", "order"], name="content_con_page_id_7de962_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentonpage",
            constraint=models.UniqueConstraint(
                fields=("page", "content"), name="unique_page_content"
            ),
        ),
    ]
